### ISSUE TITLE
Experiment paramters for objective dection with yolov3

### ISSUE THREAD

**Issue by fangliancheng** [jmiemirza/DUA#2]
Hi Jehanzeb,

Thanks for the great work! 

I am wondering could you release the hyper-parameter settings for objective detection task on SODA10M --> KITTI? For example, the data augmentation used, momentum_pre, decay_factor, minimum_momentum, batch size, number of samples used.

Best regards,
Liancheng

**Comment by jmiemirza** [comment]
Hi Liancheng, 

I am glad you like our work. 

So the hyper-parameter settings are kept same for all experiments. The data augmentations are also kept same for all experiments (as mentioned in our experiments setting). This of course also includes the momentum_pre, decay_factor, minimum_momentum, batch size. 

For the number of samples used, please refer to the Table. 1 in our supplemental material. 

Best Regards, 
Jehanzeb.

**Comment by fangliancheng** [comment]
Thanks!
