### ISSUE TITLE
About the Pre-trained model on CIFAR-10-C

### ISSUE THREAD

**Issue by tianshuocong** [jmiemirza/DUA#3]
Hi!
Thanks for the nice paper.
Could you please provide the checkpoint of the ResNet-26 you used to compare the utility with TTT and NORM? Thank you for your help in advance!

**Comment by jmiemirza** [comment]
Hi, 

You can download the checkpoint from here: https://drive.google.com/file/d/12I_4qlChWMeigej3KcCtU0JyGI69tOxo/view?usp=sharing

Best,

**Comment by tianshuocong** [comment]
Hi!

Thanks for your reply, it works for me.

Have a nice day!
