### ISSUE TITLE
How to draw Figure 2?

### ISSUE THREAD

**Issue by WentaoTan** [jmiemirza/DUA#4]
That is a really well-thought-out article! The figures are also neatly done! 
I would like some advice on how to draw figure 2.  Thank you!

**Comment by jmiemirza** [comment]
Hi, 

Thank you for your interest. The figure was drawn by saving the activation responses from the last batch normalization layer. In ResNet-26, the dimension of the output feature vector is 64. Now for each channel we can fit a distribution. This distribution is plotted. Basically each row is a single activation distribution (64 rows in total). 

Although, we used the python library (Joyplot), but a lot of things needed to be tweaked. Specially to keep the scaling factors constant for all the channels. 

Hope this helps. 

Best,
