### ISSUE TITLE
Which Python version did you use?

### ISSUE THREAD

**Issue by JohannesK14** [jmiemirza/DUA#6]
Hi and thanks for making your code publically available!

I have some trouble setting up an environment with `pip install -r requirements.txt`

No matter which python version I use, I ran into one or another library complaining over something (using conda and Ubuntu 20.04).

Could you please specify your python version?

**Comment by jmiemirza** [comment]
Hi, 

Thank you for your interest. Since the work was done 2 years ago. I do not exactly remember the python version used. But I do not believe that the error should be because of the python version. 

Also, judging from the issue you have opened, I cannot really understand the problem. Please provide more details if you would like some help on it. 

Best,

**Comment by JohannesK14** [comment]
Hi,

Thank you for your reply. I believe it should be Python 3.7. Otherwise it there is a first error for matplotlib, as with >3.7 platform.linux_distribution() got removed. Check [Stackoverflow](https://stackoverflow.com/questions/64693212/pip3-error-attributeerror-module-platform-has-no-attribute-linux-distribut)

The requirements for torch and torchvision I had to specify like so:
```
torch==1.10.2 --index-url https://download.pytorch.org/whl/cu113v
torchvision==0.11.3 --index-url https://download.pytorch.org/whl/cu113
```

Afterwards I get several errors due to conflicting versions:

The user requested numpy==1.13.3
    coremltools 6.1 depends on numpy>=1.14.5
    matplotlib 2.1.1 depends on numpy>=1.7.1
    onnx 1.12.0 depends on numpy>=1.16.6

The user requested protobuf==4.21.9
    coremltools 6.1 depends on protobuf<=4.0.0 and >=3.1.0
    onnx 1.12.0 depends on protobuf<=3.20.1 and >=3.12.2

The user requested scipy==0.19.1
    seaborn 0.11.2 depends on scipy>=1.0

The user requested matplotlib==2.1.1
    pycocotools 2.0.6 depends on matplotlib>=2.1.0
    seaborn 0.11.2 depends on matplotlib>=2.2

However, if I relax the version numbers, I can get your code to work. Thank you for posting it.

**Comment by jmiemirza** [comment]
I see. Thank you for the information. I will try to run the code again (in the next days), starting from a clean environment to update the `requirement.txt`.
